/**
 * @file nixie_driver.h
 * @author Shuqi Xiao
 * @brief LED-nixie driver
 * @version 1.0
 * @date 2021-04-24
 * 
 */

#ifndef _NIXIE_DRIVER_H_
#define _NIXIE_DRIVER_H_

#include <msp430.h>

#define NIXIE_ENABLE_PORT_OUT_0  P6OUT 
#define NIXIE_ENABLE_PORT_OUT_1  P6OUT
#define NIXIE_ENABLE_PORT_OUT_2  P6OUT
#define NIXIE_ENABLE_PORT_OUT_3  P6OUT

#define NIXIE_ENABLE_PORT_DIR_0  P6DIR
#define NIXIE_ENABLE_PORT_DIR_1  P6DIR
#define NIXIE_ENABLE_PORT_DIR_2  P6DIR
#define NIXIE_ENABLE_PORT_DIR_3  P6DIR

#define NIXIE_ENABLE_CHANNEL_0 BIT0
#define NIXIE_ENABLE_CHANNEL_1 BIT1
#define NIXIE_ENABLE_CHANNEL_2 BIT2
#define NIXIE_ENABLE_CHANNEL_3 BIT3

#define NIXIE_CTRL_PORT_DIR_0 P6DIR // dot
#define NIXIE_CTRL_PORT_DIR_1 P6DIR // A
#define NIXIE_CTRL_PORT_DIR_2 P4DIR // B
#define NIXIE_CTRL_PORT_DIR_3 P7DIR // C
#define NIXIE_CTRL_PORT_DIR_4 P7DIR // D
#define NIXIE_CTRL_PORT_DIR_5 P8DIR // E
#define NIXIE_CTRL_PORT_DIR_6 P8DIR // F
#define NIXIE_CTRL_PORT_DIR_7 P4DIR // G

#define NIXIE_CTRL_PORT_OUT_0 P6OUT // dot
#define NIXIE_CTRL_PORT_OUT_1 P6OUT // A
#define NIXIE_CTRL_PORT_OUT_2 P4OUT // B
#define NIXIE_CTRL_PORT_OUT_3 P7OUT // C
#define NIXIE_CTRL_PORT_OUT_4 P7OUT // D
#define NIXIE_CTRL_PORT_OUT_5 P8OUT // E
#define NIXIE_CTRL_PORT_OUT_6 P8OUT // F
#define NIXIE_CTRL_PORT_OUT_7 P4OUT // G

#define NIXIE_CTRL_CHANNEL_0 BIT4
#define NIXIE_CTRL_CHANNEL_1 BIT5
#define NIXIE_CTRL_CHANNEL_2 BIT3
#define NIXIE_CTRL_CHANNEL_3 BIT0
#define NIXIE_CTRL_CHANNEL_4 BIT4
#define NIXIE_CTRL_CHANNEL_5 BIT1
#define NIXIE_CTRL_CHANNEL_6 BIT2
#define NIXIE_CTRL_CHANNEL_7 BIT0

void InitNixieGpio(void);
void ClearNixie(void);
void DisplayOneDigit(int, int);

#endif